# ====================================
# Versions Catalog - SignaturePad
# ====================================

[versions]
# Build Tools
agp = "8.13.1"
kotlin = "2.2.21"
composeMultiplatform = "1.7.1"

# Code Quality
detekt = "1.23.8"
detektComposeRules = "0.4.23"

# KotlinX
kotlinxDatetime = "0.7.1"

# Testing
junit = "4.13.2"

# Publishing
vanniktech-maven-publish = "0.34.0"

[libraries]
# ====================================
# Testing
# ====================================
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }

# ====================================
# Code Quality
# ====================================
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detektComposeRules = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektComposeRules" }

# ====================================
# KotlinX
# ====================================
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }


[plugins]
# ====================================
# Build Plugins
# ====================================
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Code Quality
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# Publishing
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
